### ISSUE TITLE
Frequent error in switch.py in homeassistant logs.

### ISSUE THREAD

**Issue by bdraco** [Kane610/aiounifi#9]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 309, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 576, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/usr/src/homeassistant/homeassistant/components/unifi/switch.py", line 204, in is_on
    return self.port.poe_mode != "off"
  File "/usr/src/homeassistant/homeassistant/components/unifi/switch.py", line 249, in port
    return self.device.ports[self.client.sw_port]
AttributeError: 'NoneType' object has no attribute 'ports'
2019-12-09 04:29:24 ERROR (MainThread) [aiounifi.api] Couldn't find key: 'None'
2019-12-09 04:29:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved

**Comment by niemyjski** [comment]
I'm also seeing this.

**Comment by Kane610** [comment]
This is an issue when for some reason a client gets wrongfully marked as being powered by poe. I haven't figured out what characteristics that makes this happen. It is also problematic to do since it doesn't happen too often and what is needed is the snapshot of the client and device at the time of creating the entity.

A poor work around is to disable and then enable POE control to get rid of the faulty entities. But I think it will not be a part of hass until next release 0.109

**Comment by Kane610** [comment]
@bdraco would you mind investigating this yourself? There must be some data in the client that can be used to not create a poe switch

**Comment by bdraco** [comment]
I forgot I even opened this.  I haven't had a chance to get unifi re-enabled since the UDMP switch over.  I'll take a look as soon as I can.

**Comment by Kane610** [comment]
There is no rush. This issue has existed for a long time, it is hard to catch it in the act and I've prioritised improving other aspects of UniFi.

**Comment by bdraco** [comment]
I just re-enabled and I haven't seen this pop up.  It used to stream down the log.  I'll report back in a few days to so if it happens over time.

**Comment by bdraco** [comment]
No longer happening

**Comment by Kane610** [comment]
Not impossible that it will come back. I'd be surprised if I solved it earlier this year 🤪
